sudo: false
language: java
dist: precise
group: edge
addons:
  apt:
    packages:
      - oracle-java9-installer
jdk: 
 - oraclejdk8
 - oraclejdk9
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/.gradle
env:
  global:
  - GRADLE_OPTS="-Xmx2g -Dmaven.javadoc.skip=true"
script: 
- ./gradlew clean cleanGenerateXtext build createLocalMavenRepo -PuseJenkinsSnapshots=true -PcompileXtend=true -PignoreTestFailures=true --refresh-dependencies --continue --stacktrace

